### PR TITLE
Be responsive

### PR DESCRIPTION
**Pull request by ulysses4ever**

### CODE REVIEW

**Comment by Pat-Lafon** [comment]
I tried this out locally and this looks good to me. Thanks! I'll make some of the other changes you mentioned in the issues. One thing I don't know about for the mobile version, the list of buttons like "News", "People", etc looks to not scale so well. I.E. you would need to side scroll to get to the seminars button which is probably the most important of the buttons there. Do you have any suggestions for this? If so, that would be great otherwise I will just merge this as is

**Comment by ulysses4ever** [comment]
Good point! BTW, even the horizonal scrolling design wasn't easy to figure out! But I picked this design for the menu because it seemed fine (that's what the Amazon app does now it less, for instance) and was easiest to implement without adding the whole Bootstrap in here (to get the hamburger button).

But good point about the Seminars button. Let's maybe rearrange the buttons? E.g. putting them after People would make most sense, I think.

**Comment by Pat-Lafon** [comment]
Do you have an opinion just wrapping the buttons in the same way that pictures wrap to the next time? I'm not a UX person so I'm not sure what is better.

**Comment by ulysses4ever** [comment]
I'd be fine with wrapping but I am also fine with the current state, and the current state has the advantage that it's already implemented. I also can add that it doesn't work out of the box: when I added an absolutely minimal change so that the whole design works on mobile, the buttons got screwed: they were overlapping. So, I had to look into what to do about them. The standard thing people do with menus on mobile is collapsing them under the hamburger button. This is the Bootstrap way, and it requires adding the whole Bootstrap, which I didn't want. One of the alternatives to the hamburger button that I was able to google is the horizontal scrolling... Just wrapping sounds fine too. They will eat more vertical space that way, and maybe it'd be wise to change their design a bit to make them take less space, but that's not critical.

**Comment by Pat-Lafon** [comment]
Fair. I'm similarly not excited by a hamburger button. Lets merge this and I'll add it to my todo list to look into one day...

**Comment by ulysses4ever** [comment]
Great, thanks!

**Pull request merged**
